name: Build Test on Main Branch

on:
  push:
    branches: [main]
  pull_request: # Also run on pull requests targeting main
    branches: [main]

permissions:
  contents: read # Only read permissions needed for checkout

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install build dependencies
        run: pip install build

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist-artifact-test
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }} (Test)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU (for Linux arm64, ppc64le) - Optional
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,ppc64le

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD_LINUX: >
            yum install -y alsa-lib-devel portaudio-devel || (apt-get update && apt-get install -y libasound2-dev libportaudio-dev) || echo "ALSA or PortAudio dev libs not installed, build might fail if C ext needs them"
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_WINDOWS: AMD64 ARM64
          CIBW_SKIP: "cp37-* pp3*"
          CIBW_TEST_COMMAND: "echo 'No tests configured for wheels yet'" # Placeholder
          CIBW_TEST_REQUIRES: "" # Placeholder
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-artifact-test-${{ matrix.os }}
          path: wheelhouse/*.whl

  # No publish job in this workflow 